apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "brevesapi.name" . }}-cm"
  labels:
{{ include "brevesapi.labels" . | indent 4 }}
data:
  EXPOSE_PORT: {{ .Values.port | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  BREVES_VAULT_SERVICE_HOST: {{ tpl .Values.brevesVaultService.host . | quote }}
  BREVES_VAULT_SERVICE_PORT: {{ .Values.brevesVaultService.port | quote }}
  REDIS_HOST: {{ tpl .Values.redis.host . | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
