apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "brevesapi.name" . }}-dpl"
  labels:
{{ include "brevesapi.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
{{ include "brevesapi.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "brevesapi.labels" . | indent 8 }}
      annotations:
        kubectl.kubernetes.io/default-logs-container: {{ include "brevesapi.name" . }}
    spec:
      {{- with .Values.podSecurityContext }}
      podSecurityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "brevesapi.name" . }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - configMapRef:
            name: {{ include "brevesapi.name" . }}-cm
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        lifecycle:
          {{ toYaml .Values.lifecycle | nindent 10 }}
        env:
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwtSecretKey
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: redis-password
